### PR TITLE
Fixed Registry Key path setter

### PR DESCRIPTION
**Pull request by ader1990**

### CODE REVIEW

**Comment by EricZimmerman** [comment]
is this just a formatting thing?

**Comment by ader1990** [comment]
Hello, for me it did not compile on Visual Studio 2015.

**Comment by EricZimmerman** [comment]
yea you need updated version for the new C# stuff.

**Comment by ader1990** [comment]
You might also leave it just for readability purposes, as there will be a get and a set defined the same way.

**Pull request closed without merging**
