### PR TITLE
first step of conversion for netcore

### PR DESCRIPTION
**Pull request by julichan**

### CODE REVIEW

**Comment by EricZimmerman** [comment]
looks fine, but for the main project, can you adjust it to be:

<TargetFrameworks>net46;netstandard2.0</TargetFrameworks>

so that it keeps building 4.6? i would probably keep the test project the same vs 472, but that matters less than the main project. i plan to fully have things over to .net core 3 when it is finalized, but for now we are in an in between state.

**Comment by julichan** [comment]
I do not mind adding net47 but adding net46 (at least net461) leads to a major problem when in conjunction with netstandard2.0: the build tool prioritise referencing net46 over netstandard from a netstandard project. I want to avoid this at all cost. So, sorry, i cannot use net46 for my usage.

**Comment by julichan** [comment]
Net460 and net462 should be fine i think.

**Comment by EricZimmerman** [comment]
works for me. 460 will work with 462 as well

RE still uses 4.6 is all, and i dont want to jump thry hoops to build when i do updates =)

**Comment by julichan** [comment]
Good i ll do that when i have time

**Pull request merged**
